Update sites-de-emprego.md
ti-no-canada/imigracao-para-o-canada pull request #28
Opened 2021-10-05 14:09 UTC by PedroMarianoAlmeida

Adding https://lmia.work/

2021-10-05 14:35 UTC, MarcosCostaDev requested changes

2021-10-05 14:35 UTC, MarcosCostaDev commented on Trabalhar no Canadá/sites-de-emprego.md
> +- <https://lmia.work/>
Poderia colocar no padrão dos outros?

2021-10-05 16:44 UTC, PedroMarianoAlmeida commented on Trabalhar no Canadá/sites-de-emprego.md
> +- <https://lmia.work/>
Foi!

2021-11-04 18:29 UTC, MarcosCostaDev approved these changes

2021-11-04 18:29 UTC, merged